library(tidyverse)
library(cowplot)

# 1. Load the sensitivity analysis results
# This file is generated by the updated MATLAB benchmarking loop
df <- read_csv("Sensitivity_Analysis_Results.csv")

# 2. Prepare the data
# Ensure the parameters appear in your preferred order
param_order <- c("sk", "ku", "RR", "Rampl", "bpm1", "bpm2")
df <- df %>%
  mutate(ParamName = factor(ParamName, levels = param_order))

# 3. Define the benchmarking limits (same as your original script)
# We use these to keep the X-axis consistent for each parameter's sub-plot
limits <- list(sk = c(0, 2), ku = c(0, 10), RR = c(0, 1), 
               Rampl = c(0, 1), bpm1 = c(0, 50), bpm2 = c(50, 130))

# 4. Generate the plots
# Instead of Start vs Best lines, we plot Initial Value vs Mean Error.
# This reveals if the optimizer "stalls" or finds different minima based on the start.
plots <- map(names(limits), ~{
  df_sub <- df %>% filter(ParamName == .x)
  
  ggplot(df_sub, aes(x = InitialVal, y = MeanErr)) +
    # Line to show the trend across the +/- 20% grid
    geom_line(color = "gray50", linetype = "dashed", alpha = 0.7) +
    # Points for the 5 grid locations
    geom_point(color = "firebrick", size = 3) +
    # Error bars representing the Standard Deviation across the 5 outer folds
    geom_errorbar(aes(ymin = MeanErr - StdErr, ymax = MeanErr + StdErr), 
                  width = (max(df_sub$InitialVal) - min(df_sub$InitialVal)) * 0.05,
                  color = "firebrick", alpha = 0.6) +
    scale_x_continuous(limits = limits[[.x]]) +
    labs(title = paste("Sensitivity to Start", .x), 
         x = "Initial Value (Start Point)", 
         y = "Mean Error (Lower is Better)") +
    theme_minimal() +
    theme(
      text = element_text(size = 12),
      plot.title = element_text(face = "bold", size = 13),
      panel.grid.minor = element_blank()
    )
})

# 5. Combine and Save
# Using cowplot to arrange the grid
final_plot <- plot_grid(plotlist = plots, ncol = 3)

ggsave(filename = "sensitivity_analysis_summary.png", 
       plot = final_plot, 
       width = 14, 
       height = 9, 
       bg = "white")

# Display in RStudio/Console
print(final_plot)